//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMaintainsMvC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public int EmpNo { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public Nullable<decimal> Salary { get; set; }
        [Required]
        [Display(Name="Date of Birth")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MMM-yyyy}")]
        public Nullable<System.DateTime> Dob { get; set; }
        [Display(Name ="Department")]
        [Required]
        public string DeptCode { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
